apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nithin-shop-catalog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: nithin-shop
  source:
    repoURL: https://github.com/NITHIN/nithin-shop-k8s-ecommerce
    targetRevision: main
    path: src/catalog/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nithin-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
